set ( PROJECT_VERSION_MAJOR "0" )
set ( PROJECT_VERSION_MINOR "5" )
set ( PROJECT_VERSION_PATCH "0" )
set ( PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}" )